[project]
authors = ["mokurin000 <1348292515a@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "TomatoClock"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
build = "python build.py"

[dependencies]
pyside6 = ">=6.8.1,<7"
pyinstaller = ">=6.11.1,<7"

[pypi-dependencies]
tomatoclock = { path = ".", editable = true }
